// Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.0 (Build Build 211 04/27/2016)
// Created on Wed Sep 20 13:14:54 2017

4mux 4mux_inst
(
	.SW(SW_sig) ,	// input [0:0] SW_sig
	.SW(SW_sig) ,	// input [1:1] SW_sig
	.SW(SW_sig) ,	// input [3:3] SW_sig
	.SW(SW_sig) ,	// input [4:4] SW_sig
	.SW(SW_sig) ,	// input [8:8] SW_sig
	.SW(SW_sig) ,	// input [9:9] SW_sig
	.LEDR(LEDR_sig) 	// output [0:0] LEDR_sig
);

